name: Expense Tracker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Build Docker image
        run: |
          docker build -t expense-tracker-backend -f backend/Dockerfile .

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd ~/Desktop/Project2/Expense_Tracker
          git pull origin main
          docker compose up --build -d
